version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw  # Change this password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql  # Persists data to a Docker volume



volumes:
  mysql-data: